# ========================
# Spring Boot 应用配置
# ========================
server:
  port: 8081              # 启动端口

spring:
  application:
    name: java-huikao  # 应用名称

  datasource:
    url: jdbc:mysql://121.36.92.225:3306/javahuikao
    username: javaroot
    password: javahk25
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis配置
  data:
    redis:
      host: redis-cluster.example.com
      port: 6379
      password: redis123
      lettuce:
        pool:
          max-active: 50  # 匹配线程池大小
          max-idle: 20
          min-idle: 5
      cluster:
        nodes:
          - redis-node1:6379
          - redis-node2:6379
#  sql:
#    init:
#      mode: always       # 每次启动都执行（在自己本地运行的时候设置，感觉用云数据库会冲突）
#      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/data.sql

# ========================
# MyBatis 配置
# ========================
mybatis:
  mapper-locations: classpath:mapper/**/*.xml   # 指定 Mapper XML 文件路径
  type-aliases-package: com.buaa.javahuikao.entity # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true          # 开启驼峰命名自动映射（user_name -> userName）
    cache-enabled: false                         # 关闭一级缓存（可选）

# ========================
# 日志配置
# ========================
logging:
  level:
    com.buaa.javahuikao: debug
    org.mybatis: debug       # 打印 MyBatis 执行的 SQL
  file:
    name: logs/app.log       # 指定日志输出文件（可选）